#https://www.javainuse.com/app2yaml
server:
  port: 8081
  servlet:
    context-path: /hr
spring:
  application:
    name: erp
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:db_example
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect