server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${CONTEXT_PATH:/dev}

spring:
  application:
    name: erp
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
