#https://www.javainuse.com/app2yaml
server:
  port: 8081
  servlet:
    context-path: /hr
spring:
  application:
    name: erp
  datasource:
    url: jdbc:mysql://localhost:4306/erp_db
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true